import KERMIT from '../../../../public/images/rolex-kermit.png'

export async function GET(request: Request) {
  const mockData = {
    collection:[

        {id: 0, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:1,  brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:2, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:3, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:4, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:5, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:6, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:7, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:8, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:9, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:10, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:11, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:12, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:13, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:14, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:15, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:16, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        {id:17, brand: 'Rolex', bezel: 'GMT bezel', reserv:'70 Hours', dial:'blue dial with nightvisions dots for darker places', bracelet:'steel', sort:'Divers', price: 90000, info: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum', model:'Royal Oak',serie:'', clasp:'Diver clasp', serial: '15243OR.OO.A1234KB.01' , material: '18-karat white gold', variant:'Selfwinding chronograph', diameter:'41mm', resistance:'100ATM', glass:'Sapphire crystal', img: KERMIT },
        
    ],
  };

  return Response.json(mockData);
}
